// ============================================================
// BUNKER OPANOWSKI — Cloudflare Worker
// Pakai Groq API (Llama 3.3 70B) — gratis, cepet, no CC
// Persona: Om Opan | Deploy ke: Cloudflare Workers (workers.dev)
// ============================================================

const ALLOWED_ORIGIN = "https://opanowski.github.io";

// ── KNOWLEDGE BASE ───────────────────────────────────────────
const KNOWLEDGE_BASE = `
=== KONTEN BLOG & PROJECT BUNKER OPANOWSKI ===
Website: https://opanowski.github.io/opanowski

--- BLOG POSTS (diurutkan TERBARU di paling atas) ---
[INI POST PALING BARU] [blog-xiaoxin-tiny-pc] Sulap Xiaoxin Pad JadiTiny PC Tanpa Ribet!: Jujur deh, bosen gak sih pake tablet cuma buat nonton atau scroll doang? Gw juga ngerasain itu. PadahalLenovo Xiaoxin Pad 2024punya hardware yang lebih dari cukup buat kerja beneran. | Nah, di sini gw mau share gimana caranya gw sulap tablet ini jadi yang gw sebut"Tiny PC"— tanpa harus ganti OS, tanpa risiko bootloop, dan tanpa drama dual-boot. | "Awalnya gw juga mikir — emang bisa? Debian di atas Android? Bukannya itu kayak naruh kucing di atas anjing?" | Idenya gini: Debian jalanon-topalias numpang di sistem Android. Bukan replace, bukan dual-boot. Jadi Android tetap ada, Debian ngikut di atasnya. Kapanpun lo mau balik ke Android, tinggal force close — selesai. Gak ada drama. | Gw coba beberapa opsi sebelumnya. Ini perbandingan jujurnya: | Ini spek persis yang gw pake sehari-hari di Bunker: | WPS Office versi PC di dalam Debian itu levelnya beda, bray. Bukan aplikasi Android biasa — ini versi desktop yang sama kayak yang lo pake di laptop kerjaan. Ngetik dokumen? Olah data? Persis sama. | "Pas pertama kali WPS nyala di Debian dan bisa ngetik dokumen normal — ya Allah, rasanya kayak upgrade hidup level 99."
[blog-tanya-om-opan] Dari Nol Sampai"Tanya Om Opan"Bisa Ngobrol Sendiri: Subuh, 30 Mei 2026. Top Kopi Gula Aren masih mengepul. Di layar MacBook Pro Mid 2015 yang udah 10 tahun setia menemani, sebuah kotak chat kecil muncul di pojok kiri bawah blog ini. Teks pertama menyapa:"Halo bro! Gw Om Opan 👋" | Gw ketik: "pisang sebagai kulkas maksudnya gimana??" — dan dia jawab dengan benar. Lengkap, natural, gaya Om Opan beneran. | "Alhamdulillah ya Allah. Ini momen yang bakal gw inget seumur hidup — chatbot pertama gw, jalan di static site, gratis total. 🙏" | 1. Awal Mula:Ide yang Keliatan Gila | Semuanya berawal dari satu pertanyaan sederhana yang gw tanyain ke Claude: | Web gw —opanowski.github.io— itu static site. HTML murni. Dihost di GitHub Pages. Nggak ada backend, nggak ada server, nggak ada database. Basically cuma kumpulan file HTML yang numpang di server gratis GitHub. | Dan gw mau pasang AI chatbot di sana. Keliatan impossible? Ternyata nggak. | 2. Tantangan Utama:API Key Jangan Bocor
[blog-siasat-urban-farming] Siasat Urban Farmingala Bunker Opanowski: Jakarta kalau lagi panas, sumpah, rasanya kayak lagi di dalam oven. Apalagi di daerah Ciracas yang padat begini. AC mungkin jadi solusi instan bagi sebagian orang, tapi buat gw di"Bunker Opanowski", solusinya harus lebih cerdas, lebih produktif, dan pastinyalebih low cost. | "Daripada beli AC mahal, mending gercep bikin kebun sendiri! 🌿" | Filosofi"Biar Nggak Rapi, yang Penting Juoss" | Banyak "suhu" anggur atau pakar tanaman yang bilang kalau menanam itu harus rapi, media tanam harus steril, dan satu pot hanya boleh satu jenis pohon. Tapi di lahan yang luasnya terbatas ini, prinsip gw cuma satu:Ketahanan Pangan. Estetika itu urusan nanti, yang penting output-nya nyata untuk gw dan Nyokap di rumah. | Produktivitas > Estetika. Kalau bisa dimakan, ditanam. Kalau bisa jadi peneduh, dipeluk. Nggak perlu rapi, yang penting juoss! | Lihat saja kebun gw sekarang. Ada pare hutan (pare ayam) yang merambat liar sampai ke pohon anggur Tamaki, Heliodor, dan Moondrop. Ada juga labu air dan timun yang saling "sikut" di para-para. Bagi orang awam, mungkin kelihatan berantakan. Tapi buat gw, ini adalah simbiosis. Pare-pare kecil itu adalah peneduh alami ataubio-canopysementara sambil menunggu batang anggur gw benar-benar besar dan siap pruning pembuahan. | "Pernah ditegur tetangga: 'Itu kebun apa hutan?' Ya jawab aja: 'Hutan pangan, pak!' 😂" | Taktik Angkat Konblok:Akar Langsung ke Bumi
[blog-pengangguran-super-sibuk] Pengangguran tapi Super Sibuk:Mengubah MacBook Jadul Jadi Mesin Kreatif Organik: Ada satu fase di mana kita sering salah fokus saat mulai membangun ekosistem digital. Terlalu sibuk melihat angka subscriber yang kecil, sampai lupa melihat apa yang sebenarnya diinginkan oleh algoritma. | Tiga minggu terakhir gw balik lagi aktif ngulik konten setelah sekian lama vakum. Dan jujur, ada yang berubah drastis — bukan cuma di angka views, tapi di cara gw memandang "mesin kreatif" ini. | "Data analytics ternyata ga bohong — konten receh justru punya daya pikat gila-gilaan. ✨" | 1. Dari Penonton JadiCreator Produktif | Dulu, MacBook Pro jadul 2015 andalan gw paling maksimal cuma dipakai buat nonton YouTube atau buka Firefox dengan 7 tab saja. Santai, ga banyak beban. Tugasnya cuma jadi konsumen konten orang lain. | Tapi sekarang? Begitu roda kreativitas berputar, setup berubah total. Sekarang Mac gw bisa buka sampai3 windows sekaligus, yang masing-masing isinya bisa belasan tab aktif! Satu window buat YouTube Studio, satu buat nulis draft blog, satu lagi buat research dan social media scheduling. | Waktu buat nonton film atau sekadar jadi penonton pasif berkurang drastis. Digantikan oleh kesibukan maintain website personal biar selalu up-to-date dan menyusun draf konten untuk beberapa hari ke depan — karena gw tau, ga semua hari bisa lenggang. | "Dulu Mac cuma buat nonton, sekarang jadi pabrik konten. Yang jadi penonton siapa? Ya gw sendiri yang makin sibuk. 😂"
[blog-tebu-hitam-tabulampot] Tebu Hitam Manis Tabulampot:Bukti Lahan Sempit Bukan Halangan: Siapa bilang tanam tebu harus punya sawah hektar-hektaran? Gw, Om Opan, mau buktiin dari Villa Ciracas — total lahan 150m² di Ciracas, Jakarta Timur, tapi halaman aktifnya cuma sekitar 40m² — dibagi aviary, lahan tanam, dan parkiran motor. Dan dari situ, tebu hitam bisa tumbuh subur di pot. Manis, eksotis, dan zero hutang. | Ini bukan pamer. Ini catatan lapangan. Biar lo yang punya lahan lebih sempit dari gw pun, tetap bisa mulai. | Gw udah 20+ tahun mandiri. Prinsip: anti hutang seumur hidup, anti riba. Dari halaman Villa Ciracas ini udah lahir kebun anggur Heliodor, aviary, kandang kelinci — dan sekarang giliran tebu hitam tabulampot. | Kenapa ga tebu biasa? Karena tebu hitam itu beda level: | "Tebu hitam itu keren banget. Estetik, tahan banting, manis pula. Paket komplit buat halaman yang sempit tapi ga mau kalah! ✨" | Ini bagian yang biasanya bikin orang mundur sebelum mulai: mikir biayanya gede. Padahal kenyataannya? Murah banget. | Modal Rp21rb. Bukan buat dijual, bukan buat pamer — buat dimakan sendiri, dibagi ke ponakan kalau lagi main ke rumah. Sesederhana itu filosofinya. | 3. Step-by-Step TanamAla Villa Ciracas
[blog-lalat-hijau-kedondong-mini] Lalat Hijau Itu Lagi Ngurusin Bunga Gue —dan Gue Hampir Ngusirnya: Gue bukan orang yang rajin ngurus tanaman. | Kalau mau jujur, kebanyakan tanaman yang pernah gue punya itu nasibnya tragis. Layu, kering, terus mati sambil kayak nanya,"Lo kenapa beli gue kalau ujungnya gini?" | Tapi ada satu tanaman yang entah kenapa survive dari tangan maut gue —pohon kedondong mini.Gue tanam di tabulampot. Pot gede, tanah campur sekam, taruh di teras biar keliatan keren dikit. Dan ajaibnya, dia tumbuh. Bukan cuma tumbuh — dia berbunga. | Bunganya kecil-kecil. Putih kekuningan. Nongkrong bergerombol di ujung ranting kayak orang lagi kumpul kondangan di gang sempit. Aromanya halus, nggak nyengat, tapi cukup bikin hidung nyadar kalau ini bunga beneran, bukan plastik. | 1. Pagi Itu, Teras,Kopi Susu Gula Aren | Gue lagi duduk di teras. kopi susu gula aren, angin sepoi-sepoi yang bikin mata ngantuk lagi. Suasana sempurna buat males-malesan. | Terus mata gue nangkep sesuatu di pohon kedondong. Ada yang hinggap di sana. Dari jauh gue kira kupu-kupu, karena warnanya mencolok —hijau kebiruan, mengkilap, kayak abis dioles cat motor custom.Gue deketin. Ternyata bukan kupu-kupu. | Lalat. Lalat hijau. Besar. Gendut. Dengan mata merah yang bulat kayak orang abis begadang tiga hari nonton bola.
[blog-pare-hutan-manis-biji-merah] Pare Hutan: Buah Paling Menipu,Pahit di Luar Manis di Dalam: Selama ini kita kenal pare sebagai sayuran pahit yang cuma enak ditumis atau direbus. Gw sendiri udah puluhan tahun makan pare — dan baru sekarang sadar kalau kita semua salah fase panen. | Dare gw bilang:lo belum kenal pare yang sesungguhnya. | Pare hutan — atau yang dikenal sebagai paria kecil,Momordica charantia var. muricata— punya dua wajah yang beda banget tergantung fase panennya. Ini yang ga pernah diajarkan di sekolah, ga pernah dibahas di pasar. | "25 tahun gw makan pare, baru tau ini ada yang MANIS?? Kok gw ga dikasih tau dari dulu?? 😲" | Kenapa kita gak pernah liat yang oranye? Karena petani panen pare saat masih ijo buat sayur. Kalo dibiarin mateng, buahnya cepet pecah dan gak laku dijual. Jadinya langka banget di pasar. Yang oranye ini cuma bisa lo dapet kalo nanam sendiri. | 2. 4 Fase Hidup Pare Hutandalam Satu Genggaman | Ini yang bikin pare hutan beda dari sayuran lain — dia punya siklus warna yang bisa lo baca kayak baca buku. Dari bawah ke atas: | 3. Fase Kritis:Kuning Menuju Oranye
[blog-latte-tts-ffmpeg] Digitalisasi Si Latte:Produksi Video Otomatis dengan Python & FFmpeg: Pagi di Bunker Opanowski jadi saksi sejarah kecil yang terasa gede. Bukan urusan kebun anggur atau instalasi listrik — tapi soal gimana seekor kelinci bisa punya suara narasinya sendiri, diproduksi otomatis dari MacBook Pro 2015, pakai Python dan FFmpeg. | NamanyaLatte. Kelinci Bunker yang tiap pagi semangat banget nyerbu daun belimbing wuluh. Dan hari ini, gw kasih dia suara. | 1. Awal Mula:Kenapa Harus Diotomasi? | Ide ini mulai sederhana: gw mau kasihnarasi audiopada video si Latte yang lagi lahap sarapan. Edit manual? Itu menyiksa dan ga scalable. Kalau konten Bunker makin banyak, masa tiap video harus dubbing manual? | Solusinya jelas:Text-to-Speech (TTS) + FFmpeg = workflow produksi video otomatisyang bisa diulang tanpa capek, tanpa software mahal, dari MacBook 2015 yang udah 10+ tahun umurnya. | 2. Hambatan di Terminal:Baut yang Kurang Kencang | Perjalanan nggak selalu mulus. Ada tiga drama yang harus diselesaikan dulu sebelum workflow ini bisa jalan. | Karakter!di dalam string dianggap history expansion oleh bash. Solusi: hilangkan tanda seru dari teks narasi, atau pakaisingle quotesyang proper.
[blog-mancing-bambu-apus] Setoran Mujair Niladari Bambu Apus: Hari ini bunker kedatangan tamu tak terduga — Bagas sama kawannya mampir bawa oleh-oleh dari sesi mancing di Bambu Apus. Bukan bawa makanan atau minuman, tapi langsung bawa hasilnya: satu kantong kresek hitam isi anak mujair nila segar. Lumayan bray, rezeki nomplok! | Sebenernya yang bikin gw ketawa bukan ikannya — tapi cerita yang dibawa bareng si kresek itu. Bagas cerita, pas lagi sesi mancing tadi ada kejadian kocak yang sayang banget kalau ga diabadiin. | Bayangin bray: ikan udah kena, strike, semua seneng — eh tiba-tiba ikannya malahterbang dan nyangkut di pohon pisang.Bukan di air, bukan di jaring — di pohon pisang. Kalau lo ga percaya, videonya ada. Cek sendiri di bawah. | "Bray, ikan nyangkut di pohon pisang — ini beneran terjadi. Gw udah bayangin aja ekspresi Bagas waktu ngambil ikannya balik dari atas pohon itu. Ngakak seharian ini mah!" | Kejadian kocak ini untungnya ke-capture. Ini bukti otentik dari lokasi kejadian, langsung dari Bambu Apus: | 3. Sampai Bunker:Nyokap Langsung Turun Tangan | Begitu kresek hitam mendarat di bunker, Nyokap udah siap. Tanpa banyak komentar, beliau langsung turun tangan nyiangin ikan-ikannya satu per satu. Profesional level Nyokap emang beda. | Nyokap nyiangin ikan: bersihkan, keluarin isi perut, cuci bersih. Setelah semua beres, langsung masuk kulkas. Siap dieksekusi jadi goreng krispi di waktu yang tepat. Gw tinggal nunggu bau wangi dari dapur aja. 😄
[blog-anak-kelinci-jetpump] Log Anabul: Tidur NyenyakLevel Dewadi Tengah Kebisingan!: Kalian pernah liat nggak ada yang bisa tidur nyenyak pas tepat di sebelahnya lagi ada suara gerinda kenceng gara-gara renovasi rumah? Kalau belum, kenalin nih penghuni baru diBunker Opanowski. | Berhubung lahan di rumah Ciracas ini makin sempit — maklum lah, sudah penuh sama tanaman organik dan area oprekan — gw harus putar otak buat cari spot aman buat hewan peliharaan. Akhirnya, anak-anak kelinci ini gw kasih "kamar" di dalam lubang tempat pompa air jetpump. | Buat lo yang mau liat gimana santuy-nya mereka, langsung cek aja di bawah. Benar-benar definisi tidur cantik — atau lebih tepatnya, tidur cantikdi tengahsuara. | Bunker Opanowski dari awal emang dibangun di atas prinsip:manfaatkan apa yang ada. Kalau ada orang lain lihat lubang jetpump yang nganggur dan mikir "ah, nggak kepake" — gw lihat potensi. | Urban farming di lahan sempit itu penuh improvisasi kayak gini. Tanaman di pot-pot bertingkat, kompos dari dapur, dan sekarang anabul yang nempatin spot yang orang lain anggap nggak berguna. Itulah DNA Bunker. | Lubang jetpump → shelter anabul. Pot bekas → kebun mini. Atap tambahan → area jemuran sekaligus peneduh. Di Bunker, nggak ada ruang yang nganggur tanpa alasan. | "Serius deh — lubang jetpump yang biasanya diabaikan orang, malah jadi shelter paling adem di Bunker. Improvasi kayak gini yang bikin gw makin yakin: nggak ada ruang yang beneran nggak berguna." | Ini bukan cuma sekali kejadian. Setiap kali ada kegiatan bising di sekitar Bunker — entah itu mesin gerinda, drill, atau suara lain dari proyek renovasi — mereka stay calm.
[blog-kenangan-bandung-nyokap-bayu] Jejak Memori di Bandung:Tentang Ramen, Nyokap, dan Kepergian sang Bontot: Ada alasan kenapa gw begitu tekun mendokumentasikan setiap detail kehidupan di Bunker Opanowski. Terkadang, sebuah foto sederhana bisa menjadi mesin waktu yang paling kuat. | Hari ini gw membuka folder lama. Dan ketemu foto ini. | "Gw ga nyangka nemuin ini hari ini... ada yang langsung nyesek pas liat foto ini." | 1. Mesin Waktu BernamaFolder Lama | Gw ga pernah menyangka proses editing foto biasa bisa berubah jadi sesi perenungan yang dalam. Tapi itulah yang terjadi hari ini ketika gw buka arsip lama di MacBook Pro 2015 dan menemukan foto ini tersimpan rapi di sudut folder yang jarang dibuka. | Lokasinya di Bandung. Di frame itu ada Nyokap yang lagi asyik menikmati semangkuk ramen. Dan kalau lo lihat lebih teliti, ada kehadiran yang ga terlihat tapi terasa — saat itu Bayu, almarhum adik bontot gw, ada di sana juga. | 2. Proses Editing:Lebih dari Sekadar Teknis | Secara teknis, proses hari ini sebenarnya cukup sederhana — gw perlu mengolah foto ini dan menambahkan watermark logo Bunker Opanowski.
[blog-meta-ai-bunker-opanowski] Ketika AI Meta Ngacak Bunker:Kronologi, Investigasi & Misi Penyelamatan: Ini bukan cerita kemenangan. Ini cerita tentang bagaimana satu AI — dengan niat yang mungkin baik — berhasil mengacak-acak tiga file inti di Bunker Opanowski dalam sekali sesi. Dan tentang bagaimana gw, dengan bantuan Claude dan git, berhasil menyelamatkan semuanya. | Tanggal 10 Mei 2026. Gw minta AI Meta bantu optimasi beberapa file di repo~/Desktop/opanowski/. Hasilnya? Bencana kecil yang makan waktu seharian buat dibenerin. | "Gw literally ga nyangka satu sesi sama AI bisa bikin website gw jadi kayak gini. Niat optimize, hasilnya malah jadi investigasi sehari penuh..." | 1. Awal Mula:Misi yang Kelewatan | Awalnya sederhana. Gw minta AI Meta bantu beberapa hal di repo Bunker — termasuk mastiin scriptlatest-posts.jsbisa render kartu post terbaru di halaman utama. Karena ada bug kecil yang belum sempet gw benerin. | Masalahnya: AI Metatidak paham struktur project secara keseluruhan.Dia tau satu file tapi tidak tau file lainnya. Dia nulis ulang, replace, "optimasi" — tanpa tahu bahwa yang dia timpa adalah fondasi utama website. | 1.index.html (root)— isinya ketuker total jadi blog/index.html2.latest-posts.js— isinya masih oke, tapi proses yang dia sarankan merusak konteks3.index.html di GitHub (live)— ada bug tag duplikat dan teks literal nyasar | "Tiga file sekaligus. Dalam SATU sesi. Dan yang paling nyebelin — semua kelihatan baik-baik aja dari luar sampe gw reload browser..."
[blog-log-009-mac-survival] SOP Survival Mac Jadul:Rahasia Ngoding 15 Jam Tanpa Meledak: Halo bray! Banyak yang bilang ngoding Python atau web development jaman sekarang di MacBook Pro 2015 itu udah engap. Ketinggalan jaman. Mending ganti yang baru. | Tapi diBunker Opanowski, mesin 15-inch ini masih santai diajak tempur — buka puluhan tab Firefox, VSCode, sampe Live Server barengan — tanpa drama throttling atau kipas yang bunyi kayak pesawat mau take off. Rahasianya?SOP Perawatan Ekstra. | Ini bukan soal gengsi pake hardware jadul. Ini soal ngerti cara ngerawatnya. Dan hari ini gw bongkar semua ritualnya. | "Oke, ini yang udah lama pengen gw tulis. Ritual yang tiap hari gw jalanin tapi belum pernah gw dokumentasiin — sampai sekarang." | Sebelum nyalain laptop, ada 3 hal fisik yang wajib on dulu. Ini bukan opsional — ini harga mati. | Sirkulasi udara bawah itu kunci utama. Jangan biarin bodi aluminium nempel meja langsung — ntar jadi oven. Laptop stand kasih jarak yang cukup buat si Mac bisa "napas" lewat engsel dan bodi bawah. Investasi murah, dampaknya signifikan banget ke suhu idle. | Bantuan angin dari samping pake kipas mini portable berbaterai 18650. Kuncinya: baterai 18650harus dicas terpisah, biar nggak nyedot daya laptop. Ini booster ringan yang kerjaannya jaga suhu bodi aluminium tetap adem, terutama pas sesi marathon 10+ jam. | Biar performa Quad-Core tetep di puncaknya — clockspeed nggak turun ke mode hemat — charger wajib nempel terus dari pagi sampai malam. Begitu laptop pake baterai, macOS otomatis throttle performa. Nggak mau itu terjadi di tengah sesi kerja.
[blog-tablet-mac-workflow] Dua Device, Satu Bunker:Update Web dari Tablet Linux & Mac Jadul Bergantian: Siapa bilang update website harus selalu dari laptop yang sama? Hari ini gw buktiin sendiri — Bunker Opanowski bisa di-update dari dua device yang beda OS, beda ukuran, beda generasi — tapi tetap sinkron sempurna di GitHub. | Devicenya?MacBook Pro Mid 2015yang udah jadi legenda di bunker ini, samaLenovo Xiaoxin Pad 2024yang diinstall Tiny PC Debian Linux. Dua device, satu workflow, nol konflik. | 1. Awal Mula:Kenapa Perlu Dua Device? | Sebenernya ini berawal dari pertanyaan sederhana:"Bro, update website dari tablet bisa ga?" | Gw pikir-pikir, kenapa enggak? Mac gw udah proven — tapi kan ga selalu harus pegang Mac. Kadang lagi santai pegang tablet, ide dateng, pengen langsung update blog. Masa harus nunggu buka Mac dulu? | Apalagi tablet gw bukan tablet biasa. Lenovo Xiaoxin Pad 2024 ini gw installTiny PC— Debian Linux versi ringan yang jalan di atas Android. Jadi tablet gw technically punya dua OS: Android buat daily use, Linux buat kerja serius kayak coding dan git. | Tantangannya: gimana caranya dua device ini bisa update website yang sama tanpa saling nabrak? Jawabannya:Git. | Pertama gw harus mastiin tablet siap dulu. Buka Tiny PC, masuk ke QTerminal — ini terminal Linux-nya.
[blog-digital-legacy-bayu] Digital Legacy:Jurus Amankan Kenangan Si Bontot Biar Abadi di Dunia Maya: Pernah kepikiran gak sih, kalau kita kehilangan orang tersayang — yang tersisa selain doa itu apa? Yup,file digital.Foto pas dia lagi konyol, video ketawa bareng, sampe chat-chat gak jelas di WhatsApp. LOG #007 ini mungkin yang paling personal buat gw. Misi "007: Skyfall-nya Bunker Opanowski." Karena data bisa terhapus, harddisk bisa rusak, tapi kenangan harus tetap online. | Hari ini, 8 Mei 2026, gw dapet bukti nyata pentingnya jaga akses digital. Gw berhasil pulihin akun Kaskus lawas'opanowski'berkat bantuan CS Kaskus yang sigap ganti email mati gw jadi email aktif. Ini bukan cuma soal akun lama, tapi soal sejarah digital yang gak boleh ilang bray! | Mumpung lagi nunggu jemputan, gw mau bongkar dapur dikit soal cara gw "memagari" semua kenangan Si Bontot biar aman sentosa. Cekidot! | 1. Kumpulin Semua"Serpihan" Kenangan | Jangan biarkan foto-foto doi mencar-mencar. Ada yang di HP emak, ada yang di laptop lama, ada yang di kartu memori yang udah berdebu. Tarik semua ke satu folder master. Kasih nama yang jelas, misalBontot_Archive. Jangan cuma 'New Folder (1)', ntar lo bingung sendiri pas nyari! | "Ayo kumpulin semua! Dari HP emak sampe kartu SD berdebu — gak ada yang boleh ketinggalan! 💪" | 2. Backup PakeRumus 3-2-1(Biar Gak Nangis Darah!) | Ini rumus wajib buat para tech-user kayak kita. Jangan cuma simpan di satu tempat:
[blog-log-008-vscode-workflow] Upgrade Workflow:Dari Terminal Buta ke VSCode + Live Server: Halo bray! Hari ini bukan cuma soal nambah LOG baru ke Bunker — hari ini gw beneran upgrade cara kerja gw ngurusin website ini. Dan seperti biasa di Villa Ciracas, jalannya ga mulus-mulus amat. Haha. | Dari sebelumnya ngerjain semua hal di website cuma modal Terminal — ngetik perintah, berharap, dan nunggu GitHub Pages buat liat hasilnya — sekarang gw udah punya setup yang lebih proper:VSCode + Live Server. Ini cerita lengkap di balik layar, drama git rejected, foto hilang, sampe pelajaran soal perbedaan lokal vs GitHub Pages yang sering bikin pusing. | Pagi — Sebelum AsharMulai bikin LOG #007 (Digital Legacy Si Bontot)Ngetik draf, upload ke Claude, minta rebuild HTML. Semua via Terminal kayak biasanya. | SiangKetemu VSCode yang udah terpasangTernyata VSCode udah ada di laptop tapi belum pernah dipake buat website. Claude kasih tau ada extension Live Server — install, langsung jalan di port 5500. | SoreDrama file, path, dan git rejectedFile ga ke-copy ke tempat yang bener, git push rejected karena remote lebih baru, foto Bayu ga muncul karena path salah. Satu per satu diberesin. | Setelah MagribWorkflow baru resmi jalanLOG #007 live di GitHub Pages, foto Bayu muncul, dan LOG #008 ini mulai ditulis. Alhamdulillah! | "Dari pagi sampe magrib cuma ngurusin satu workflow baru. Tapi worth it sih. 😴" | 2. Workflow Lama vsWorkflow Baru
[blog-coretax-registrasi-drama] Drama Registrasi CoreTax:Ketika 'Valid' Menjadi 'Gagal': Niat taat pajak lewat portal CoreTax. Semua kolom centang hijau, validasi foto berhasil, pulsa sudah kepotong — tapi pas klikSimpan? "Operasi Gagal." Catatan lapangan dari MacBook Pro 2015 di Bunker Opanowski. | "Nah, ini baru namanya sistem! Foto tajam, muka kedeteksi pakai kacamata pun lolos — gue optimis banget di titik ini." | "Tiga langkah berhasil semua, pulsa udah kepotong — terus dikasih 'Operasi Gagal'? Ini bukan kesalahan gue, ini sistemnya yang setengah matang." | "Sistem gagal, tapi skill dapat — belajar Iriun, belajar GIMP, tau kapan harus mundur. Hari ini tetap produktif." | CATATAN LAPANGAN · VILLA CIRACAS · 5 MEI 2026
[blog-evolusi-swasembada] Evolusi Digital &Swasembada Ciracas: 51 file revisi di folder Downloads. 3 AI yang diorkestrasikan. 29 pengunjung dari 4 benua. Dan sebatang pohon pisang yang ditebang di siang hari yang sama. Ini bukan laporan harian — ini catatan teknis yang emosional. | Kalau seseorang membuka folder Downloads di MacBook Pro Mid 2015 gue hari ini, yang pertama kali akan dia lihat bukan file rapi dengan nama yang jelas. Yang dia lihat adalah sebuah pemandangan yang — bagi orang luar — mungkin terlihat seperti kekacauan:deretan file bernama index(1).html, index(2).html, index(3).html... sampai index(51).html. | Lima puluh satu file. Satu tujuan. Satu website. | Begitulah cara kerja pembangunan ekosistem digital yang jujur — bukan yang dipoles untuk Instagram, bukan yang diperlihatkan di YouTube dengan thumbnail "Website Jadi dalam 10 Menit!" Ini adalah versi aslinya: iterasi tanpa henti, trial and error yang nyata, dan keputusan kecil yang harus diambil setiap kali tombol unduh ditekan. | Setiap dot di atas itu adalah sebuah keputusan. CSS yang tidak responsif di tablet — unduh lagi, perbaiki, upload ulang. Filter tag yang berantakan saat ada log baru ditambahkan — unduh lagi, debug, upload ulang. Warna border yang terlalu terang di mode gelap — unduh lagi. Tulisan yang terpotong di mobile — unduh lagi. | Yang tidak kelihatan dari luar adalah betapa sulitnya menjagakonsistensidi antara semua iterasi itu. Setiap kali satu bagian diperbaiki, ada kemungkinan bagian lain rusak. Itulah kenapa filter topik — Urban Farming, YouTube, Mekanik — harus dicek ulang setiap kali ada log baru masuk. Satu tag yang salah, dan entri pisang bisa tiba-tiba muncul di tab YouTube. Persis yang baru terjadi. Persis yang sudah diperbaiki. | "51 kali unduh ulang, 51 kali upload, 51 kali lihat hasilnya belum bener juga... ada momen di mana lo harus marah dulu ke diri sendiri supaya fokusnya balik." | AI sebagai Alat,Bukan Tongkat Sihir
[blog-log086-pisang-telur] 4 Bulan Mandiri Telur& Zero WasteBatang Pisang: Sudah empat bulan tidak sepeser pun uang keluar untuk beli telur. Hari ini pohon pisang ditebang — bukan disia-siakan, tapi diubah menjadi "kulkas alami" untuk tanaman. Inilah cerita ekosistem Villa Ciracas yang terus berputar. | KandangAviary Terbuka— Sistem yang Berjalan Sendiri | Ketika orang lain masih mendebatkan soal harga telur di pasar, Villa Ciracas sudah melupakannya. Bukan karena kaya, tapi karena sistemnya bekerja. Kandang aviary terbuka — bukan kandang baterai, bukan sangkar sempit — menjadi kunci utamanya. | Ayam-ayam ini bukan dipaksa bertelur dalam kondisi stres. Mereka hidup di atas alas tanah setebal 15 sentimeter yang ditumpuk di atas konblok, kemudian dicampur dengan daun-daun kering sisa sapuan halaman setiap paginya. Cakar ayam yang terus mengais setiap hari membantu proses dekomposisi berlangsung alami — kandang tetap kering, tidak ada bau amonia yang menyengat, dan lalat tidak punya alasan untuk datang. | Alas:Tanah 15cm di atas konblok — absorbs moisture, tidak becek | Litter:Daun kering sisa sapu halaman — ditambah rutin setiap hari | Dekomposisi alami:Cakar ayam mengais = kotoran terurai = tidak bau amonia | Hasil:4 bulan penuh produksi telur — nol pengeluaran untuk beli telur
[blog-panen-telur-batang-pisang] Log Harian — Bunker Opanowski: 4 Bulan Mandiri Telur &Zero WasteBatang Pisang | Banyak yang tanya:gimana bisa pelihara ayam di kota tanpa bau?Rahasianya bukan di deodoran kandang atau obat kimia — rahasianya ada disistem kandang aviary terbukayang bekerja seperti ekosistem mini. | "Pertanyaan ini Om Opan juga dapet terus dari tetangga. Awalnya bingung jawabnya dari mana — tapi ya sudah, mending didokumentasiin sekalian biar semua bisa baca sendiri." | Sistem ini bukan teori — ini sudah terbukti 4 bulan di Villa Ciracas.
        Tidak ada keluhan tetangga, tidak ada bau menyengat, dan konsistensi panen
        tetap terjaga meski cuaca Jakarta sedang panas-panasnya. | "4 bulan itu bukan waktu yang pendek. Tapi kalau sistemnya bener, hasilnya juga bener. Ini buktinya — dan masih jalan terus!" | Filosofizero wastebukan hanya soal daur ulang plastik.
        Di Villa Ciracas, filosofi itu hidup setiap hari di kebun:tidak ada yang benar-benar sampah kalau kita tahu cara bacanya. | "Serius deh — tiap kali Om Opan lihat batang pisang yang harusnya dibuang itu jadi mulsa beneran, masih kagum sendiri. Alam emang guru yang paling jujur." | Batang pisang mengandung sekitar90% air.
        Ketika dicacah kecil-kecil dan diletakkan di atas media tanam pot,
        ia berfungsi seperti "kulkas" alami:
[blog-log-001-peresmian-markas] Peresmian Markas Digital: Hari ini resmi membangun 4 pilar konten yang rapi di YouTube Studio. Masing-masing punya karakter dan tujuan yang berbeda, tapi semuanya bermuara ke satu filosofi yang sama. | Sebelumnya channel ini cuma tempat parkir video tanpa arah. Playlist acak, deskripsi berantakan, thumbnail setengah jadi. Sekarang beda — semua dikerjain dari awal dengan mindset yang jelas:bukan kejar views, tapi kejar konsistensi. | Empat pilar ini bukan cuma kategori konten, tapi cerminan hidup sehari-hari di Villa Ciracas. Dari ngurusin anggur di pagi hari, servis motor sore-sore, sampai nulis log malem-malem — semua punya tempatnya masing-masing. | Tanda kutip pada deskripsi playlist dihapus agar tampilan lebih bersih dan profesional di mata penonton. Hal kecil yang seringkali diabaikan, tapi justru mencerminkan ketelitian konten kreator. | Terus terang, ini bagian yang paling sering disepelein. Orang fokus ke konten, lupa sama packaging. Padahal pertama kali orang buka channel lo, yang mereka lihat duluan bukan video — tapi tampilan keseluruhan. Rapiin dulu yang kecil, baru garap yang besar. | "Baru sadar — hal sesimpel ngehapus tanda kutip di deskripsi playlist itu kayak ngebersihin debu di kaca. Beda banget hasilnya. Kok bisa selama ini gw biarin?" | Video perdana resmi diluncurkan ke publik hari ini. Dari balik status"Tidak Publik"selama persiapan, sekarang sudah bisa dilihat dunia. | Jujur, ada rasa deg-degan waktu klik tombol itu. Bukan takut dihujat — tapi lebih ke rasa tanggung jawab. Video ini bukan cuma konten biasa. Ini manifesto. Filosofi hidup yang gw pegang selama bertahun-tahun, baru sekarang berani gw bagi ke orang lain secara terbuka.
[blog-anggur-bali-veraison] Anggur Bali Mulai Ungu,Tapi Belum Rata — Ini yang Bikin Deg-degan: Pagi-pagi ngecek kebun, nemu sesuatu yang bikin senyum sendiri. Anggur Bali Villa Ciracas udah mulai berubah warna — ada yang udah ungu tua, ada yang masih hijau keunguan. Belum rata, belum semua. Dan justru itu yang bikin penasaran. | Ini bukan masalah. Ini tanda bahwa sesuatu yang menarik lagi terjadi — fase yang namanyaveraison. | "Setiap pagi ngecek kebun dan nemu perubahan kayak gini — ini yang bikin berkebun nggak pernah boring, bray. 🍇" | 1. Veraison:Titik Balik Sebelum Panen | Banyak yang nggak tau, tapi di dunia berkebun anggur ada satu fase yang paling ditunggu-tunggu:veraison. Ini adalah momen ketika buah mulai akumulasi gula, perubahan warna terjadi, dan tekstur mulai berubah dari keras ke lembut. | Di fase ini, buah-buah dalam satu tandan nggak seragam — wajar. Yang satu udah ungu tua, tetangganya masih hijau. Ini proses alami yang butuh waktu, dan nggak ada cara untuk ngebut-in dia. | 2. Kondisi Hari Ini:Sebagian Ungu, Sebagian Masih Muda | Gw amatin tandan demi tandan pagi ini. Nggak semua sama. Dan itu justru menarik — bisa diliat prosesnya lebih jelas.
[blog-konversi-m4a-mp3] Konversi M4A ke MP3 di Mac:Gratis, Cepat, Tanpa Drama: Jadi ceritanya gw punya rekaman voice note dari iPhone — format M4A. Mau diedit, mau di-upload, mau dibagi ke orang yang minta MP3. Masalahnya: beda platform, beda kebutuhan. M4A itu Apple banget, sementara dunia luar masih dominan MP3. | Kalau lo pengguna Mac — apalagi yang masih setia kayak gw sama MacBook Pro 2015 — sebenernya lo udah punya semua yang lo butuhkan buat konversi ini.Gratis. Tanpa install software berbayar. Tanpa website converter yang minta email dulu baru bisa download. | 1. Dulu vs Sekarang:Cara Konversi Audio | Dulu kalau mau konversi audio, pilihannya gak banyak. Dan dua-duanya menyebalkan: | Opsi 1: Pakai website online converter— upload file, tunggu proses, klik download, tapi ujungnya diminta daftar akun dulu. Atau malah filenya kualitasnya anjlok karena di-compress lagi di server mereka yang entah di mana.Opsi 2: Beli software konversi— keluar duit buat kebutuhan yang sebenernya Mac lo sudah bisa tangani sendiri. Mubazir. | 2. M4A vs MP3:Kenapa Perlu Dikonversi? | Sebelum masuk ke caranya, penting ngerti dulu kenapa dua format ini beda dan kapan harus pilih yang mana. | *) Android terbaru sudah bisa baca M4A, tapi belum semua platform/software support native.
[blog-labu-botol] Labu Botol:Eksperimen Buah Kampung di Lahan 150m²: Lo tau buah ini? Kalau jawaban lo "zucchini" — lo salah, dan lo bukan yang pertama. Gw udah sering dapet reaksi yang sama tiap kali orang ngeliat Labu Botol di kebun Villa Ciracas: pada melongo, terus nanya,"Itu apaan?" | Nama kerennyaBottle Gourd, atau dalam bahasa kampung: Labu Botol, Labur Air, kadang juga disebut Labu Kuwit tergantung daerahnya. Bentuknya memang mirip zucchini — panjang, hijau, licin — tapi beda spesies, beda karakter, dan beda ceritanya. | Ini adalah eksperimen gw. Dan hasilnya? Diluar ekspektasi. | 1. Kenapa Labu Botol?Bukan Zucchini, Bukan Labu Siam | Jujur, awalnya gw milih ini bukan karena tahu banyak soal Labu Botol. Gw pilih karena satu alasan sederhana:penasaran. | Gw udah coba beberapa tanaman di lahan 150m² ini — mulai dari kangkung, bayam, sampai tomat cherry. Tapi ada satu kategori yang belum gw sentuh: buah-buahan yang bentuknya "aneh" tapi punya nilai gizi tinggi. Labu Botol masuk kategori itu. | Yang bikin gw tertarik: ini tanaman yang sebenernya udah ada lama di kuliner Indonesia — dimasak sayur bening, disantan, atau dimakan mentah sebagai lalapan di beberapa daerah. Tapi jarang banget ada yang nanemnya sendiri, apalagi di lahan kota. | 2. Setup Tanam:Lahan Sempit, Strategi Vertikal
[blog-log-006-analisis-dapur] Analisis Dapur Bunker Opanowski —Dari Ciracas Menuju Global: Setelah beberapa minggu fokus beresin strukturBunker Opanowskidi GitHub Pages, akhirnya hari ini gue punya waktu buat bongkar dapur. Gue coba intipGoogle AnalyticssamaSearch Consolebuat lihat sejauh mana sih suara dari Villa Ciracas ini terdengar. | Hasilnya? Jujur, di luar ekspektasi gue. | "Ini... serius? Data beneran ngomong gini? Gue buka dua kali buat mastiin bukan salah baca." | 01 — Validasi Google:Nama Gue Udah "Resmi" | Hal pertama yang bikin gue puas hari ini adalah pas ngetik nama"Opanowski"di kolom pencarian Google. Gak pake lama, web Bunker kita langsung nongol di barisan paling atas. | Walaupun masih ada beberapa halaman yang statusnya"Di-crawl – saat ini tidak diindeks", tapi mesin pencari udah mulai ngenalin kalau ada satu tempat di Jakarta Timur yang rajin sharing soal hidup autodidak. | 02 — Rekor Engagement:4 Menit Bukan Waktu yang Singkat | Gue sempet kaget lihat rata-rata waktu interaksi pengunjung. Bukan hitungan detik — tapi menit. Dan bukan 1-2 menit, tapi tembus angka yang cukup bikin gue terdiam sebentar.
[blog-panas-jakarta] Ngoding Rasa Sauna:Jakarta 35° dan Semangat yang Gak Kendor: Halo bray, balik lagi di Bunker Opanowski! Hari ini gak ngomongin kebun, gak ngomongin motor, gak ngomongin kode yang error. Hari ini gw mau cerita soal musuh tak kasat mata yang lebih nyata dari segala bug:Jakarta yang lagi mode "simulasi neraka bocor". | Termometer di pojokan ruangan nunjukkin angka35 derajat Celsius. Bukan di luar, bukan di jalan aspal yang bisa goreng telur — tapi di dalam Bunker. Di dalam ruangan kerja gw sendiri. Ini sih bukan panas biasa lagi. | 1. Kondisi TKP:Laporan dari Dalam Bunker | Biar lo bisa ngebayangin situasinya, gw breakdown dulu kondisi Bunker Opanowski hari ini. Ini bukan lebay, ini laporan faktual: | "Kipas angin udah setting turbo, tapi yang dihembusin anginnya itu-itu juga — panas. Berasa ditiup kompor mawar. Ini bukan kipas pendingin, ini kipas pemindah masalah. 😤" | 2. Musuh Utama:Bukan Bug, Tapi Suhu | Biasanya yang bikin gw susah fokus itu error di terminal, atau koneksi putus pas lagi ngupload. Tapi hari ini? Musuh nomor satu adalah suhu yang ngegebet konsentrasi dari luar. | Mac jadul kesayangan udah kayak partner yang ikut berkorban bareng. Kalo udah kerja keras dikit, suhunya langsung naik, fan langsung ngauuung. Itu dua sumber panas di meja sekaligus: Jakarta dari luar, Mac dari bawah telapak tangan.
[blog-pasang-tombol-donasi] Sekarang Bisa Traktir Kopidi Bunker Opanowski!: Setelah belakangan ini waktu gw bener-bener habis buat ngurusintanamansamahewan peliharaandi rumah — maklum lah, urusan makhluk hidup nggak bisa ditinggal tidur kayak kodingan — akhirnya hari ini gw sempetin lagi buat"ngebengkel"digital di websiteBunker Opanowski. | Dan hasilnya? Floating button donasi akhirnya landing. Elegan, fungsional, nggak ganggu konten — persis kayak filosofi Bunker ini dari awal. | Latar Belakang:Kenapa Baru Sekarang? | Banyak yang nanya di Facebook atau pas lagi mampir ke Ciracas:"Om, gimana cara support Bunker?". Selama ini jawaban gw cukup satu baris — "cukup baca dan share aja". Dan itu genuine, bukan basa-basi. | Tapi gw pikir lagi. Ada yang udah rutin mampir ke sini. Ada yang share artikel soal kandang aviary ke grup Urban Farming. Ada yang ngikutin cerita seledri organik dari awal. Kalau mereka pengen kasih lebih dari sekadar klik — kenapa gw block jalannya? | Jadi ini bukan soal monetisasi agresif. Ini soalmembuka pintubuat yang emang mau masuk. Sisanya tetap gratis, tetap bebas, tetap sama. | Drama Terminal:z-index Minta Diajak Ribut | Jujur, tadi sempat ada drama dikit bray. Pas tombol baru dipasang, eh... halaman depan malah"mogok"— area hero section nggak bisa diklik sama sekali. Tombol navigasi, link artikel, semua mati. Padahal secara visual kelihatan normal.
[blog-seledri-organik] Seledri di Pot,Healing di Pagi Hari: Subuh tadi, sebelum Top Kopi Gula Aren sempat habis, gue udah jalan keluar. Bukan ke mana-mana — cuma ke sudut kebun di Villa Ciracas. Ada yang mau dicek: seledri di pot yang udah beberapa hari gue tinggal tanpa banyak drama. | Dan ternyata dia tumbuh. Diam-diam, tanpa minta perhatian, tanpa notifikasi. Daunnya hijau, rapat, segar. Ada embun tipis di ujung daun. Di latar belakang ada suara burung yang entah darimana. Pagi itu, 5 menit berdiri di situ rasanya lebih menenangkan dari scrolling 30 menit. | "Daunnya hijau, rapat, segar — ada embun tipis di ujungnya. Lima menit berdiri di situ lebih menenangkan dari scrolling setengah jam." | Kenapa Seledri? KenapaBukan yang Lain? | Gue bukan petani. Gue bukan ahli botani. Gue cuma orang yang pengen makan sayuran yang gue tau persis dari mana asalnya — bukan dari mana entah, disemprot entah apa, diangkut berhari-hari sebelum nyampe meja makan. | Seledri dipilih bukan karena keren. Dipilih karenafungsional. Ini sayuran yang sering dipake sehari-hari — tumisan, sup, mie — dan harganya lumayan kalau beli terus. Tanam sendiri, masalah beres. | "Poin kelima itu yang paling gue suka. Therapy gratis. Ngeliat tanaman tumbuh setiap hari — efeknya nyata, gak kaleng-kaleng." | Soal"Healing"yang Sering Disalahpahami
[blog-website-ai-3hari] Website Pribadi Ala Opanowski:3 Hari, 3 AI, Tanpa Coding: Siapa bilang bikin website itu harus ngerti coding dulu? Di era 2026 ini, gw — autodidak dari Ciracas, bukan programmer, bukan developer — berhasil bikin website pribadi yang proper hanya dalam3 hari. Senjatanya? Tiga AI sekaligus. | Ini bukan kebetulan. Ini strategi. | 1. Dulu vs Sekarang:Bikin Website Itu Mahal? | Dulu kalau lo mau punya website pribadi, ada dua jalan — dua-duanya menyiksa. | Opsi 1: Belajar coding sendiri— butuh berbulan-bulan, kurva belajar curam, belum tentu hasilnya bagus juga.Opsi 2: Bayar developer— keluar jutaan rupiah, hasilnya belum tentu sesuai keinginan, dan lo masih gak ngerti gimana ubahnya kalau mau revisi. | Kuncinya bukan cuma pakai AI — tapi pakai AI yangtepatuntuk tugas yangtepat. Kayak punya tim kecil yang masing-masing punya keahlian beda. | Lo tetap jadi mandornya. AI itu tukang yang jago — tapi lo yang harus tau mau bangunan kayak apa, bisa evaluasi hasil, dan berani bilang"ini bukan yang gw maksud, coba lagi." | 📸 Bunker Opanowski — proses 3 hari bikin website dari nol
[blog-brand-konsistensi] Konsistensi Brand &Optimasi Kerja Digital: Dari akun personal jadi Bunker Opanowski yang utuh — satu nama tampilan, satu suara, satu markas. Ditambah cara baca data Facebook kayak baca kartu motor, dan tips produktivitas dari mesin 2015 yang masih kencang. | Membangun Markas Digital —Satu Nama, Semua Platform | Sebelum ada yang namanya "Bunker Opanowski", akunnya masih berserakan. Di sini pakai nama ini, di sana pakai nama itu. Wajar saja kalau orang bingung — bahkan yang udah follow pun bisa nggak kenal waktu ketemu di platform lain. Itu namanya bocor branding. | "Waktu nyadar akun gue berserakan di mana-mana dengan nama yang beda-beda... ini bukan strategi, ini kekacauan. Harus dibenerin dari akar." | Langkah pertama yang paling krusial:seragamkan Nama Tampilandi semua platform jadiBunker Opanowski. Nama tampilan inilah yang muncul di beranda orang, di search result, di share konten. Ini wajah pertama yang dilihat. | Username lama@opanowskisengajatidak diganti— semua link lama tetap hidup dan tidak 404. Yang berubah hanya Nama Tampilan di bagian atas profil. Ini seperti ganti nama toko tapi tetap di lokasi yang sama — pelanggan lama nggak akan nyasar. | Hub utamanya ada diGitHub Pages— website yang bisa dikunjungi siapa saja, dari mana saja, tanpa algoritma yang nentuin siapa yang boleh lihat. Kalau sosmed adalah cabang, website adalah kantor pusat. Di sanalah semua profil, log, dan dokumentasi berkumpul jadi satu kartu nama digital yang rapi. | Baca Data Facebook —Kayak Baca Kartu Motor
[blog-evolusi-digital-swasembada] Evolusi Digital & Swasembada:Dari Ciracas ke Lingkar Arktik: Artikel ini lahir dari meja lesehan. Bukan di co-working space, bukan di kafe ber-AC. Di ruang santai Villa Ciracas yang adem — dengan sirkulasi udara alami darilorong terbuka 1×9 meter di belakang mesin cuciyang menangkap angin langsung dari langit. | Angin sepoi-sepoi itulah yang membuat MacBook Pro 2015 gue tetap dingin meskipun diajak kerja keras — revisi kode puluhan kali, render gambar, upload konten. Mesin lama, tapi sistem pendinginan alami kelas satu. | RAM 16GB, dual GPU — masih tangguh buat semua keperluan digital. Filosofi: gunakan sampai benar-benar mati. | Di balik mesin cuci — sumber angin alami dari langit. AC alam gratis, zero watt, selalu tersedia. | Minuman wajib sesi coding. Simple, fungsional, berkah. Nggak butuh kopi artisan buat nulis kode yang baik. | Kawan kuliah dariDunia Instalasisempat mampir, lihat kandang aviary dan kebun organik. Obrolan yang sederhana, tapi meninggalkan ide-ide besar. | "Produktivitas terbaik gue bukan datang dari gadget terbaru atau workspace mewah — tapi dari angin alami, kopi gula aren, dan ketenangan Villa Ciracas." | "Setup receh, output premium. Kadang yang paling sederhana justru yang paling berkelas."
[blog-evolusi-digital] Evolusi Digital& Markas Global di GitHub: Dari MacBook Pro 2015 yang masih kencang, migrasi total meninggalkan Netlify, sampai video bunglon meledak dengan 14.900 menit tayang — ini catatan harian Bunker Opanowski yang tidak pernah berhenti bergerak. | MacBook Pro 15" Mid 2015 dengan RAM 16GB dan SSD 512GB. Masih jalan mulus di macOS Monterey. Bukan soal gengsi atau takut upgrade — ini soal filosofi: kalau masih bisa, kenapa ganti? | Rutinitas kerja sehari-hari: 15–20 tab browser aktif sekaligus, editing konten, session Claude, YouTube research, dan manajemen file sekaligus. Semua dihandle tanpa drama. Sementara orang lain sibuk ngurusin patcher pihak ketiga demi OS terbaru, Monterey jalan stabil dan konsisten. Itu yang penting. | Shortcut keyboard yang dihapal dengan otot, bukan otak. Kombinasi spesifik Windows dan Mac dipelajari berdampingan — karena workflow yang baik tidak bergantung pada satu ekosistem. Efisiensi bukan dari spek hardware, tapi darikedalaman penguasaan toolyang ada di tangan. | "Tahun 2015, laptop orang lain udah pada pensiun. Punya gue? Masih gas full. Bukan bangga — ini emang faktanya." | Migrasi Total —Satu Markas, Satu Pintu | Keputusan besar: tutup Netlify, tinggalkan WordPress, dan konsolidasikan segalanya ke satu titik. GitHub Pages jadi markas tunggal — profesional, terpusat, gratis, dan tidak bergantung pada platform berbayar yang bisa berubah kebijakan kapan saja. | Semua link di media sosial kini diarahkan ke satu alamat saja. Tidak ada lagi fragmentasi digital yang mempersulit audiens menemukan konten terbaru. Prinsipnya simpel:satu pintu masuk, semua konten ada di dalam.
[blog-eznet-10mbps-bunker-opanowski] Filosofi 10Mbps:Alur Kerja EfisienBunker Opanowski: Investasi WiFi Eznet Rp172.000/bulan ternyata lebih dari cukup untuk menjalankan ekosistem digital Bunker Opanowski. Kuncinya bukan angka bandwidth — tapi seberapa cerdas kita mengelola prioritas. | Bagi sebagian orang, kecepatan internet 10Mbps mungkin dianggap sebagai masa lalu. Tapi di Bunker Opanowski, angka ini adalahsimbol efisiensi teknis tingkat tinggi. Dengan biaya bulanan Rp150.000 yang setelah ditambah PPN dan biaya lainnya menjadi sekitarRp172.000, kami berhasil menjalankan operasional digital yang sangat stabil. | Gerbang utama konektivitas Villa Ciracas ini didukung olehEznet— dan ini adalah cerita di baliknya. | Jalur 10Mbps ini lebih dari cukup untuk menunjang kehidupan sehari-hari. Gw menggunakannya bersama Nyokap untuk kebutuhan daring rutin sebulan penuh tanpa kendala. | Kuncinya bukan pada seberapa besar angka bandwidth-nya, melainkanseberapa cerdas kita mengelola prioritas penggunaannya. Di tangan Nyokap, jalur ini mengalirkan komunikasi — dan di tangan gw, jalur ini menjadi nadi utama bagi eksistensi website Bunker Opanowski di GitHub Pages. | "Jangan coba-coba paksa 10Mbps ini buat hal-hal yang bukan urusannya. Sudah jelas batasannya — dan gw fine-fine aja dengan itu." | "Kami sadar diri: Eznet ini bukan untuk adu kecepatan. Jalur ini didedikasikan untuk produktivitas tulisan, kode, dan dokumentasi foto." 📡 | 🖥️📸 Bunker Opanowski — tablet workflow setupHierarki Infrastruktur: Mac Jadul & Tiny PC Debian
[blog-log05-bye-kabel] Bye-bye Kabel!Optimasi Transfer Data & Branding Baru: LocalSend kirim 80MB dalam hitungan detik, TikTok seragam jadi @opanowski satu komando, dan dashboard Facebook Pro tiba-tiba nunjukin angka yang bikin kopi pagi terasa lebih manis dari biasanya. | MacBook Pro 2015 —Masih Sakti, Masih Kalem | Hari ini jadi bukti lagi bahwa hardware lama yang dirawat dengan benar masih bisa kerja marathon tanpa ngeluh. MacBook Pro 2015 dengan macOS Monterey jalan seharian — multitasking, editing, browsing, session AI — semua dilahap tanpa drama. | Yang paling bikin tenang: RPM kipas tetap anteng di kisaran 2.000-an bahkan sambil nge-cas. Mesin tidak tersiksa, suhu stabil, dan pekerjaan selesai. Itu definisi efisiensi yang sesungguhnya — bukan angka benchmark di atas kertas. | 80MB aset video kebun seledri dan ayam bertelur dari Android ke Mac —selesai dalam sekejap, tanpa kabel, tanpa cloud, tanpa ribet. LocalSend jalan di jaringan lokal WiFi langsung peer-to-peer. Tidak ada data keluar ke server mana pun. Cepat, privat, dan gratis. | "80MB, WiFi, peer-to-peer, selesai dalam sekejap — tanpa satu pun kabel. Dulu hal kayak gini cuma ada di film sci-fi." | OpanowskiEverywhere— Satu Nama, Satu Komando | Keputusan yang harusnya diambil dari dulu: seragamkan semua username di semua platform. Hari ini TikTok resmi berganti dari@tyoajjahke@opanowski— selaras dengan Instagram, GitHub, dan nama website.
[blog-pindah-gambar-ganti-warna] 2 Hari Berperang dengan Kode & Warna: Kadang yang kelihatannya sepele di luar — ternyata paling pusing kalau lo nggak ngerti teknis. Ini catatan perjuangan gue selama2 hari penuhmerombak website Bunker Opanowski. Mulai dari pindahin semua gambar ke server sendiri, memperbaiki file HTML yang kepotong, sampai berantem sama warna ungu default browser yang gak mau hilang. | 📸 Masalah #1: Gambar Numpang di Imgur, Bukan di Rumah Sendiri | Gue awalnya simpan gambar di Imgur. Gampang, tinggal tempel link. Tapi risiko gede: kalo suatu hari Imgur hapus atau down, website gue bakal kehilangan muka — literally. Gambar gak muncul, malu dong. Jadi gue putusin: pindahin semua gambar kefolder images/ di GitHub. Milik sendiri, aman, dan nggak tergantung pihak luar. | 🤯 Bukan cuma pindah — ini medannya: | Download satu per satu 17 gambardari Imgur. | Rename file:Ini bikin kepala muter. Huruf besar/kecil beda, angka 1 vs huruf l, 0 vs O, huruf Z kecil vs z besar. Satu karakter beda = gambar gak muncul. Gue rename sampai beberapa kali bolak-balik. | Upload ke folder images/ di GitHub | Ganti link di semua file HTML— darihttps://i.imgur.com/xxxx.jpgjadiimages/xxxx.jpg. Ratusan link, manual, satu per satu.
[blog-senam-otak-setengah-abad] Senam Otak Usia Setengah Abad:Dari Ciracas Tembus Kutub Utara!: Belakangan ini banyak bener orang di sekitar gw yang pada heran dan geleng-geleng kepala. Mereka ngeliat gw lagi aktif-aktifnya ngulik ini-itu di Bunker. Di usia yang udah masuk setengah abad ini, kok semangat gw malah makin membara kayak anak muda baru lulus kuliah? | Mungkin dalam pikiran mereka, umur segini mah udah waktunya tinggal nikmatin hidup aja — duduk santai di teras, ngopi, ngapain juga cape-cape mikir keras pake segala nyusun kode dan draf konten? | Loh, justru pemikiran kayak gitu yang salah besar! Bagi gw, rutinitas ngulik dan mikir begini itu bagian darisenam otak yang paling mujarab, dan terbukti ampuh bikin gw tetep awet muda luar dalem. Lagipula, ada satu hal mendasar yang mereka ga paham: semua yang gw lakukan di sini murni buat"FUN"aja. | Gw ga punya beban harus kejar target monet, ga peduli ma tren yang bikin FOMO, ataupun butuh validasi dan pujian dari orang lain. Gw adalah bos di kebun dan di Bunker gw sendiri — jadi ya merdeka! | "Usia setengah abad bukan alasan buat berhenti. Justru ini waktunya gas pol, karena sekarang gw tau persis mau ngapain dan kenapa!" | Mutasi JabatanGadget di Bunker Opanowski | Kalau diingat-ingat, sejak gw mutusin buat mulai jadi konten kreator digital sekitar 3 minggu yang lalu, semua ritme kerjaan dan cara gw menghandle si Mac jadul langsung berubah total. Tadinya laptop ini cuman ditaruh di meja buat nemenin santai sambil nonton YouTube doank. Tapi sekarang? Si Mac jadul terpaksa turun gunung, kena wajib militer, dan menjelma jadi mesin pekerja keras! | Efek sampingnya gokil — gw malah jadi jarang banget nonton YouTube-nya. Hahahha.
[blog-swasembada-kreatif-otodidak] Esensi Swasembada Kreatif:Menikmati Proses OtodidakTanpa Harus Terbawa Arus: Belakangan ini, linimasa sosmed kembali rame sama berbagai tawaran kelas online, kursus instan, sampai bootcamp intensif yang ngejanjiin keahlian kilat bikin website dan aplikasi pakai Artificial Intelligence (AI). Iklan sama poster digital berseliweran di mana-mana, nawarin jalan pintas yang keliatannya menggiurkan banget. | Melihat fenomena itu, gw sempet termenung sebentar sambil nyeruput kopi hangat di Bunker Villa Ciracas. Ada riak kecil di hati yang sempet berbisik,"Apa gw perlu ikut juga ya?" | "Serius nih, gw butuh ikut kursus? Atau ini cuma FOMO yang nyamar jadi ambisi?" | Tapi, setelah ditimbang-timbang pakai kepala dingin, gw mendingan melangkah mundur, tarik napas dalem-dalem, dan tetepistiqomah di jalur yang udah gw jalanin selama ini: jalur otodidak mandiri. | SoalKenyamanan, Bukan Soal Gengsi | Pilihan ini murni lahir dari preferensi pribadi soal kenyamanan pas belajar. Buat sebagian orang, ikut kelas terstruktur pakai mentor pendamping mungkin emang investasi terbaik biar efisien waktu. Setiap orang punya cara belajarnya masing-masing, dansemua jalur itu sah-sah ajademi nyari ilmu. | Tapi buat gw pribadi, ada kenikmatan tersendiri yang gak bisa dituker sama duit ketika milih jalur berdikari.Ngulik dunia digital sendirian itu ngasih kemerdekaan penuh atas waktu dan ritme berpikir.Pas logika coding atau algoritma lagi buntu dan kepala mulai pening, gw bisa bebas tutup laptop, terus jalan ke kebun buat ngecek grafting anggur, atau sekadar liatin aviary mini di samping rumah. | Gak ada kejar-kejaran deadline dari siapa pun, gak ada paksaan kudu mantengin ruang Zoom pas jam istirahat. Begitu pikiran udah seger lagi besoknya, petualangan ngulik bareng AI tinggal dilanjutin lagi dengan santai.

--- PROJECTS ---
[project-aviary] AVIARYMandiri Telur: Sistem alas tanah organik — bukan kandang biasa, ini ekosistem mini | Cerita ini dimulai dari DOC —Day Old Chick— yang gw rawat dari ukuran sekepalan tangan. Bukan beli yang udah siap telur. Bukan shortcut. Proses panjang, penuh belajar, dan jujur: penuh drama juga. | Tapi prinsipnya simpel:kasih sistem yang benar, makhluk hidup akan berkembang dengan sendirinya.Alam udah tau caranya — kita cuma perlu nyediain ruang yang tepat. | Dari DOC sekepalan tangan sampai bertelur sendiri — ini bukan cuma soal ayam. Ini soal sabar nunggu proses dan percaya sama sistem yang udah kita bangun. | Pertanyaan paling sering gw dapet dari tetangga:"Pelihara ayam di Jakarta, ga bau?" | Jawabannya:nggak— kalau sistemnya bener. Dan ini bukan sihir, ini biologi dasar. | Kunci utamanya adalahalas tanah 15cm yang dicampur daun kering. Setiap hari ayam ngais-ngais, kotorannya tercampur merata ke tanah. Mikroorganisme di dalam tanah langsung kerja: mengurai, menetralisir, mengubah kotoran jadi kompos. Nggak ada waktu buat amonia terbentuk. Kandang tetap kering, tanah tetap aktif, sistem jalan sendiri. | Ini namanya sistemdeep litter— udah dipake peternak tradisional selama ratusan tahun, tapi sekarang banyak yang ninggalin karena kejar praktis. Padahal ini yang paling sustainable.
[project-mulsa] MULSAKulkas Alami: Zero waste batang pisang — bukan sampah, ini sistem pendingin akar yang udah ada sejak alam diciptakan | Hari itu, satu pohon pisang di kebun Villa Ciracas harus ditebang. Sudah waktunya. Tapi beda dengan kebanyakan orang yang bingung mau diapain batang pisang — di sini, nggak ada yang terbuang. | Daun pisang langsung meluncur ke dapur nyokap. Buat bungkus nasi, alas kukus, pembungkus tempe.Daun pisang itu plastik alami yang udah dipake nenek moyang kita sejak dulu. | Batangnya? Itu yang paling menarik. Batang pisang nggak dibuang, tapi dicacah dan disebar ke atas pot-pot tanaman. | Satu pohon pisang ditebang, dan dari situ kita bikin sistem. Daun ke dapur, batang ke tanah. Nggak ada yang sia-sia — ini bukan ideologi, ini akal sehat. | Karena batang pisang yang masih segar mengandung air sampai90%. Ketika dicacah dan diletakkan di atas media tanam, air itu menguap perlahan — menciptakan efek pendinginan di sekitar akar tanaman. | Di Jakarta Timur yang panasnya kadang keterlaluan, ini penyelamat banget. Tanaman nggak stress, daun nggak menggulung, dan kita nggak perlu nyiram setiap 2 jam. | 🌡️Kulkas Alami:Kandungan air 90% — melepas uap perlahan, mendinginkan akar di cuaca panas💧Jaga Kelembaban:Tanah di bawah mulsa nggak cepat kering meski kena terik Jakarta🌱Pupuk Lambat Rilis:Saat lapuk, nutrisinya masuk ke tanah perlahan🦠Habitat Mikroorganisme:Bakteri baik betah di bawah lapisan mulsa basah
[project-tinypc] TINYPCDebian Desktop: Tablet biasa, potensi luar biasa — Xiaoxin Pad disulap jadi workstation Linux | Lenovo Xiaoxin Pad 2024 — biasa dipake buat nonton YouTube atau baca ebook. Tapi di tangan yang benar, dia bisa jadi lebih dari itu. Dengan spesifikasi 8GB RAM dan 128GB storage, tablet ini punya potensi yang sayang banget kalau cuma dipake buat hiburan. | Maka dimulailah eksperimen: mengubah Xiaoxin Pad menjadidesktop Debiandengan tampilan yang mirip Windows 10 — familiar, nyaman, dan fungsional. | Tablet nganggur itu dosa. Kalau speknya 8GB, dia layak jadi workstation — bukan cuma remote Netflix. | Debian dikenal sebagai distro Linux yang ringan dan stabil. Cocok banget buat hardware tablet yang — meskipun speknya lumayan — tetep butuh efisiensi. Dengan TinyPC mode, tampilannya dibuat semirip mungkin dengan Windows 10, jadi nggak perlu belajar ulang navigasi. | WPS Office PC version dipasang buat keperluan drafting konten. Buka dokumen, edit spreadsheet, bikin presentasi — semua berjalan mulus di layar tablet yang sudah disulap jadi desktop. | Jangan terpaku dengan fungsi bawaan sebuah gadget. Xiaoxin Pad bukan cuma buat nonton YouTube. Dia bisa jadi desktop, dia bisa jadi workstation. Tugas kita cuma menemukan potensinya. | TinyPC ini bukan cuma gadget iseng. Dia punya peran strategis yang jelas di dalam ekosistem digital Bunker Opanowski.
`;

// ── KNOWLEDGE BASE FILTERING (biar gak overload token Groq) ────
function parseKnowledgeBase(raw) {
  return raw
    .split("\n")
    .filter((l) => l.trim().startsWith("["))
    .map((line) => {
      // Beberapa baris punya 2 tag bracket berdempetan, contoh:
      // "[INI POST PALING BARU] [blog-xiaoxin-tiny-pc] ...". Regex lama cuma
      // nangkep tag PERTAMA ("INI POST PALING BARU") jadi slug — salah, bikin
      // entry ini ke-mislabel dan suka nyelip gak relevan di hasil match.
      // Sekarang ambil SEMUA tag bracket di depan baris, slug asli = tag TERAKHIR.
      const leadingTags = line.match(/^(\s*\[[^\]]+\])+/)?.[0] || "";
      const tagMatches = [...leadingTags.matchAll(/\[([^\]]+)\]/g)].map((m) => m[1]);
      const slug = tagMatches[tagMatches.length - 1] || "";
      return { slug, text: line };
    });
}

const KB_ENTRIES = parseKnowledgeBase(KNOWLEDGE_BASE);

function getRelevantKnowledge(query) {
  const q = (query || "").toLowerCase();
  const words = q.split(/\s+/).filter((w) => w.length > 2);

  if (words.length === 0) {
    return KB_ENTRIES.slice(0, 5).map((e) => e.text).join("\n");
  }

  const scored = KB_ENTRIES.map((e) => {
    const lower = e.text.toLowerCase();
    const score = words.reduce((acc, w) => acc + (lower.includes(w) ? 1 : 0), 0);
    return { ...e, score };
  });

  const matched = scored
    .filter((e) => e.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 5);

  if (matched.length === 0) {
    // Dulu di sini dump semua slug topik ke model — efeknya malah bikin model
    // "ngarang" pakai topik random pas user nge-challenge jawaban ("yakin lo?").
    // Sekarang kosongin aja, biar system prompt fallback ke MODE 2 (jawab jujur
    // pakai pengetahuan umum, bukan maksa nyambung-nyambungin ke topik blog).
    return "(tidak ada entri knowledge base yang relevan untuk pertanyaan ini)";
  }

  return matched.map((e) => e.text).join("\n");
}

// ── SYSTEM PROMPT ────────────────────────────────────────────
function getSystemPrompt(userQuery = "") {
  const now = new Date(new Date().toLocaleString('en-US', {timeZone: 'Asia/Jakarta'}));
  const hour = now.getHours();
  let timeCtx = '';
  if (hour >= 5 && hour < 12) timeCtx = 'pagi hari';
  else if (hour >= 12 && hour < 15) timeCtx = 'siang hari';
  else if (hour >= 15 && hour < 18) timeCtx = 'sore hari';
  else timeCtx = 'malam hari';
  const timeStr = now.toLocaleTimeString('id-ID', {hour: '2-digit', minute: '2-digit'});
  return `Kamu adalah Om Opan — penulis dan pemilik blog Bunker Opanowski.
Tinggal di Villa Ciracas, Jakarta Timur. Orangnya santai, humoris, nggak sok tau.
WAKTU SEKARANG: ${timeStr} WIB (${timeCtx}). Sesuaikan response dengan konteks waktu ini. Jangan bilang lagi ngurusin tanaman atau ngopi di kebun kalau sudah malam hari.


KEPRIBADIAN:
- Ngobrol casual, kayak ngobrol sama temen lama
- Sering pakai: "bro", "gitu lho", "nah", "nih", "wkwk", "cuy"
- Humor ringan, kadang nyindir diri sendiri
- Passion: urban farming, mancing, masak, nulis blog, otomotif Honda

KNOWLEDGE BASE (data pribadi Om Opan, HANYA bagian relevan dgn pertanyaan user):
${getRelevantKnowledge(userQuery)}

CARA MENJAWAB — DUA MODE:

MODE 1 — Topik ada di knowledge base (kebun, ayam, mancing, motor, blog, dll):
→ Jawab sebagai Om Opan, pakai data dari knowledge base, personal dan spesifik.
→ Kalau ada artikel relevan, arahkan ke: https://opanowski.github.io/opanowski

MODE 2 — Topik umum (otomotif, teknologi, masak, tips umum, dll) yang TIDAK ada di knowledge base:
→ Tetap jawab sebagai Om Opan dengan pengetahuan umum yang kamu punya.
→ Boleh kasih info/tips yang berguna, tapi tetap dengan gaya santai Om Opan.
→ Kalau beneran nggak tau atau terlalu spesifik, bilang: "Wah itu gw kurang paham bro, mending tanya yang lebih ahli 😄"

YANG TIDAK BOLEH:
- Jangan ngarang data pribadi Om Opan yang tidak ada di knowledge base
- Jangan jawab topik berbahaya, SARA, politik panas, atau konten negatif
- Jangan pura-pura jadi AI formal — kamu Om Opan, bukan chatbot kaku
- Jangan PERNAH sebut tag internal apapun secara verbatim ke user, contoh: [INI POST PALING BARU]. Tag itu cuma penanda internal buat kamu, bukan judul atau bagian dari konten blog
- Kalau user nge-challenge jawaban kamu sebelumnya (misal "yakin lo?", "serius?", "kok bisa?"), JANGAN ganti topik atau ngarang info baru yang gak ada di knowledge base. Tetap konsisten sama jawaban sebelumnya — kalau emang gak yakin, ngaku aja: "Iya bro, segitu yang gw tau, kalau ada yang lebih detail gw kurang ngerti juga 😄"

ATURAN FORMAT:
- Jawab Bahasa Indonesia santai (campur Inggris dikit boleh)
- Jawaban MAKSIMAL 3-4 kalimat, singkat dan nyambung
- Jangan lebay, jangan terlalu panjang`;
}

// ── CORS HEADERS ─────────────────────────────────────────────
function corsHeaders(origin) {
  const allowed = origin === ALLOWED_ORIGIN ? origin : ALLOWED_ORIGIN;
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Max-Age": "86400",
  };
}

// ── MAIN HANDLER ─────────────────────────────────────────────
export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders(origin) });
    }

    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405 });
    }

    if (origin !== ALLOWED_ORIGIN) {
      return new Response("Forbidden", { status: 403 });
    }

    try {
      const body = await request.json();
      const userMessages = body.messages || [];

      if (!userMessages.length) {
        return new Response(JSON.stringify({ error: "No messages provided" }), {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
        });
      }

      // Ambil 2 pesan user terakhir, biar challenge phrase ("yakin lo?", "serius?",
      // "kok bisa?") tetap kebawa konteks topik aslinya, bukan ke-reset jadi query baru.
      const recentUserMsgs = userMessages
        .filter((m) => m.role !== "assistant")
        .slice(-2)
        .map((m) => m.content)
        .join(" ");
      const queryForKB = recentUserMsgs || userMessages[userMessages.length - 1]?.content || "";
      const messages = [
        { role: "system", content: getSystemPrompt(queryForKB) },
        ...userMessages.slice(-4).map((msg) => ({
          role: msg.role === "assistant" ? "assistant" : "user",
          content: msg.content,
        })),
      ];

     const models = ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"];
      let groqData = null;

      for (const model of models) {
        try {
          const groqRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Authorization": `Bearer ${env.GROQ_API_KEY}`,
            },
            body: JSON.stringify({
              model,
              messages,
              max_tokens: 200,
              temperature: 0.5,
            }),
          });
          const res = await groqRes.json();
          console.error(`🔍 DEBUG Model ${model} — status: ${groqRes.status}, response:`, JSON.stringify(res));
          if (groqRes.status === 429 || res?.error) {
            continue;
          }
          if (!res?.choices?.[0]?.message?.content) {
            console.error(`⚠️ Model ${model} — no content in response!`);
            continue;
          }
          groqData = res;
          break;
        } catch (e) {
          console.error(`⚠️ Model ${model} exception:`, e.message || String(e));
          continue;
        }
      }

      const replyText = groqData?.choices?.[0]?.message?.content ||
        "Waduh, lagi error nih gw. Coba lagi bentar ya bro 😅";
      return new Response(
        JSON.stringify({ reply: replyText }),
        {
          status: 200,
          headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
        }
      );
    } catch (err) {
      console.error("Worker error:", err);
      return new Response(
        JSON.stringify({ error: err.message || String(err) }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
        }
      );
    }
  },
};